spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.10.100:5432/deposit_service_database
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 15672
    host: http://localhost
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

server:
  port: 9999